[23:51:54>ERROR] load.load_app:Failed to Import Module: C:/dev/Code/Github/TRasPI/programs/System Information/
Traceback (most recent call last):
  File "C:\dev\Code\Github\TRasPI\core\sys\load.py", line 141, in _load_py_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/dev/Code/Github/TRasPI/programs/System Information/main.py", line 4, in <module>
    import memory
  File "C:/dev/Code/Github/TRasPI/programs/System Information\memory.py", line 2, in <module>
    from home.app import App
ModuleNotFoundError: No module named 'home.app'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\Code\Github\TRasPI\core\sys\load.py", line 123, in load_app
    return validate_app(_load_py_file(path))
  File "C:\dev\Code\Github\TRasPI\core\sys\load.py", line 147, in _load_py_file
    raise core.error.load.ModuleFileImport(name, path) from e
core.error.load.ModuleFileImport: Failed to Import Application '<System Information-5>' from 'C:/dev/Code/Github/TRasPI/programs/System Information/' cause ModuleNotFoundError: No module named 'home.app'
